"use client";

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

type Language = "ru" | "en";
type LocaleValue = { language: Language; toggle: () => void; t: (value: string) => string };
const LocaleContext = createContext<LocaleValue>({ language: "ru", toggle: () => undefined, t: (value) => value });

// Russian remains the source copy; this catalogue also covers text added dynamically by the demo.
const phrases: Record<string, string> = {
  "Услуги": "Services", "Демо": "Demo", "Стоимость": "Pricing", "Контакты": "Contact", "Написать в Telegram": "Message on Telegram", "Обсудить проект": "Discuss a project", "Попробовать демо-бота": "Try the demo bot", "Открыт к новым проектам": "Available for new projects", "Наверх": "Back to top",
  "Telegram-боты": "Telegram bots", "и автоматизация": "and automation", "для бизнеса": "for business", "Telegram мини-приложения": "Telegram Mini Apps", "AI-интеграции": "AI integrations", "Автоматизация": "Automation", "Решения вокруг Telegram": "Telegram solutions", "От первого сообщения клиента до понятной заявки у менеджера.": "From the first client message to a clear request for your team.", "Подробнее": "Learn more",
  "Разрабатываем решения под ключ: связываем между собой сервисы, настраиваем автоматические процессы, AI-помощников, Telegram Mini Apps и разворачиваем всё на сервере, чтобы система работала стабильно 24/7.": "We build end-to-end solutions: connect services, set up automated processes, AI assistants and Telegram Mini Apps, then deploy everything on a server for reliable 24/7 operation.", "Интеграции": "Integrations", "Единая система вместо разрозненных сервисов": "One system instead of disconnected services", "Логика, данные и уведомления — в одном потоке.": "Logic, data and notifications — in one flow.",
  "Услуги, цены, FAQ, запись, сбор заявок, квалификация клиентов и передача менеджеру.": "Services, prices, FAQ, booking, lead collection, client qualification and handoff to a manager.", "Полноценные интерфейсы внутри Telegram: каталоги, запись, личные кабинеты, заказы и внутренние сервисы.": "Full interfaces inside Telegram: catalogues, bookings, client accounts, orders and internal tools.", "AI-квалификация обращений, ответы на вопросы, сводки заявок и помощь сотрудникам.": "AI lead qualification, answers to questions, lead summaries and team assistance.", "Telegram → CRM → уведомления → Таблицы Google → внутренние сервисы.": "Telegram → CRM → notifications → Google Sheets → internal tools.",
  "Попробуйте бота прямо сейчас": "Try the bot right now", "Выберите тариф и свой бизнес — бот покажет путь клиента в рамках выбранного решения.": "Choose a plan and business — the bot will show the client journey for that solution.", "Выберите тариф": "Choose a plan", "Тариф определяет функциональность сценария.": "The plan defines the scenario functionality.", "Выберите отрасль": "Choose an industry", "Каждый вариант открывает отдельный реалистичный путь клиента.": "Each option opens a distinct, realistic client journey.", "Нет нужной отрасли?": "Don't see your industry?", "Не нашли свой бизнес?": "Didn't find your business?", "Например, стоматология": "For example, dentistry", "Например, салон красоты": "For example, beauty salon", "Создать демо": "Create demo", "Демо-сценарий адаптируется под указанную сферу.": "The demo scenario adapts to the specified industry.", "Показать мой сценарий": "Show my scenario", "Вы выбрали:": "You selected:", "для": "for", "Скопировать ссылку на демо": "Copy demo link", "Ссылка скопирована": "Link copied", "Демонстрационный сценарий": "Demo scenario", "Функциональность и путь клиента зависят от выбранного тарифа.": "The functionality and client journey depend on the selected plan.", "Возможности выбранного тарифа": "Selected plan capabilities",
  "Автоматические воронки": "Automated funnels", "Базовый Telegram-бот": "Basic Telegram bot", "Продвинутый бот": "Advanced bot", "Telegram мини-приложение": "Telegram Mini App", "Сопровождение": "Support", "Популярный": "Popular", "от 10 000 ₽": "from ₽10,000", "от 20 000 ₽": "from ₽20,000", "от 50 000 ₽": "from ₽50,000", "от 100 000 ₽": "from ₽100,000", "/ месяц": "/ month", "за сценарий": "per scenario", "Простой и понятный канал для клиентов.": "A simple, clear channel for clients.",
  "Логика сообщений": "Message logic", "Сбор обращений": "Lead collection", "Передача менеджеру": "Manager handoff", "Меню услуг и цен": "Services and price menu", "Мастера и специалисты": "Specialists", "Запись через YCLIENTS": "Booking through YCLIENTS", "Сбор заявок и контактов": "Lead and contact collection", "FAQ и автоответы": "FAQ and auto-replies", "Передача администратору": "Administrator handoff", "Всё из базового тарифа": "Everything in the basic plan", "Работа с данными YCLIENTS": "Working with YCLIENTS data", "Напоминания о записи": "Booking reminders", "Повторные касания": "Follow-up messages", "Сценарии при отмене": "Cancellation flows", "Уведомления и статистика": "Notifications and analytics", "Индивидуальный интерфейс": "Custom interface", "Расписание и услуги": "Schedule and services", "Карточки специалистов": "Specialist cards", "Личный раздел клиента": "Client area", "Акции и сценарии": "Offers and flows", "Дизайн под стиль компании": "Design matching your brand", "Контроль работы": "Performance monitoring", "Исправление ошибок": "Bug fixes", "Небольшие изменения": "Small changes", "Новые сообщения": "New messages", "Корректировка сценариев": "Scenario adjustments", "Консультации": "Consultations",
  "Стоимость разработки": "Development pricing", "Финальная стоимость зависит от сценария и необходимых интеграций.": "The final price depends on the scenario and integrations required.", "Попробовать демо": "Try the demo",
  "Как проходит работа": "How the work goes", "Разбираем процесс": "We review the process", "Определяем, что сейчас сотрудники делают вручную.": "We identify what the team is doing manually now.", "Проектируем сценарий": "We design the scenario", "Строим путь клиента и логику автоматизации.": "We build the client journey and automation logic.", "Разрабатываю": "Development", "Бот / мини-приложение / интеграции.": "Bot / Mini App / integrations.", "Запуск": "Launch", "Тестирование, подключение и поддержка.": "Testing, setup and support.", "Что можно автоматизировать": "What can be automated", "Заявки": "Leads", "Запись": "Booking", "Уведомления": "Notifications", "Повторные продажи": "Repeat sales", "Работу сотрудников": "Team workflows", "AI-квалификацию": "AI qualification", "Таблицы Google": "Google Sheets", "Отчёты": "Reports",
  "Частые вопросы": "Frequently asked questions", "Сколько занимает разработка?": "How long does development take?", "Простой Telegram-бот обычно можно запустить значительно быстрее сложной системы с Mini App и интеграциями. Точный срок зависит от сценария проекта.": "A simple Telegram bot can usually launch much faster than a complex system with a Mini App and integrations. The exact timeline depends on the project flow.", "Можно подключить CRM?": "Can you connect a CRM?", "Да. Архитектура может включать CRM, YCLIENTS, Google Sheets и другие системы через API и webhooks.": "Yes. The architecture can include CRM, YCLIENTS, Google Sheets and other systems through APIs and webhooks.", "Можно сделать бота под мой бизнес?": "Can you build a bot for my business?", "Да. Сценарий проектируется под конкретный процесс компании.": "Yes. The flow is designed around your company’s process.", "Вы работаете только с Telegram?": "Do you work only with Telegram?", "Основное направление — Telegram-боты, Mini Apps и связанные бизнес-интеграции.": "The focus is Telegram bots, Mini Apps and related business integrations.", "Можно начать с небольшой версии?": "Can we start with a smaller version?", "Да. Часто разумнее сначала сделать MVP, проверить сценарий и затем расширять систему.": "Yes. It is often smarter to start with an MVP, validate the flow and then expand the system.",
  "ОБСУДИМ ЗАДАЧУ": "LET’S DISCUSS YOUR TASK", "Ваш бизнес можно": "Your business can be", "автоматизировать.": "automated.", "Расскажите, как сейчас устроен процесс, и я предложу, что в нём можно автоматизировать.": "Tell me how your process works now, and I’ll suggest what can be automated.", "Можно просто прислать ссылку на ваш сайт — я посмотрю текущий клиентский путь.": "You can simply send a link to your website — I’ll review the current client journey.", "Телефон": "Phone", "Telegram-боты • мини-приложения • AI-автоматизация": "Telegram bots • Mini Apps • AI automation",
  "Путь обращения": "Client journey", "Клиент пишет в бот": "Client messages the bot", "Сценарий": "Scenario", "Уточняет запрос": "Clarifies the request", "Сохраняет данные": "Saves the data", "Менеджер": "Manager", "Получает готовую заявку": "Receives a structured lead",
  "Демо-бот": "Demo Bot", "бот": "bot", "Сегодня": "Today", "Готово": "Done", "Так мог бы выглядеть сценарий для вашего бизнеса.": "This is how a scenario for your business could look.", "Пройти ещё раз": "Go through again", "Обсудить такого бота": "Discuss a bot like this", "Сообщение...": "Message...", "Отправить сообщение": "Send message", "Демо-режим: введённые данные никуда не отправляются.": "Demo mode: entered data is not sent anywhere.", "Начать заново": "Start again", "Вернуться назад": "Go back", "Мини-приложение": "Mini App", "Новая запись": "New booking", "Запись создана ✓": "Booking created ✓", "Карточка лида": "Lead card", "Новый клиент": "New client", "Источник: Telegram": "Source: Telegram", "Лид добавлен ✓": "Lead added ✓", "Действие подготовлено": "Action prepared", "Данные переданы в демо-режиме": "Data transferred in demo mode", "ВЫБРАННЫЙ ТАРИФ · ДЕМО": "SELECTED PLAN · DEMO", "Что получает бизнес по итогам этого пути.": "What the business receives at the end of this journey.", "Пройдите сценарий — здесь появятся данные и действия для выбранного тарифа.": "Complete the scenario — data and actions for the selected plan will appear here.", "Имитация интеграции · Демо": "Integration simulation · Demo", "✓ действие подготовлено": "✓ action prepared", "Возможности тарифа:": "Plan capabilities:", "Администратору": "Administrator", "Почта": "Email",
  "Барбершоп / Beauty / SPA": "Barbershop / Beauty / SPA", "Клининг": "Cleaning", "Автосервис / детейлинг": "Car service / detailing", "Образование": "Education", "Стоматология / клиника": "Dentistry / clinic", "Ремонт / выездные услуги": "Repairs / field services", "Недвижимость": "Real estate", "B2B услуги": "B2B services", "Услуги → запись → клиент": "Services → booking → client", "Расчёт → услуги → заявка": "Estimate → services → lead", "Услуга → авто → время": "Service → car → time", "Направление → уровень → урок": "Subject → level → lesson", "Специалист → время → контакт": "Specialist → time → contact", "Проблема → срочность → район": "Issue → urgency → district", "Цель → бюджет → район": "Goal → budget → district", "Задача → масштаб → контакт": "Task → scale → contact", "Запрос → детали → контакт": "Request → details → contact",
  "Здравствуйте!": "Hello!", "Здравствуйте 👋": "Hello 👋", "Добро пожаловать 👋": "Welcome 👋", "Что вас интересует?": "What are you interested in?", "Выберите услугу:": "Choose a service:", "Услуги и цены": "Services and prices", "Записаться": "Book now", "Оставить заявку": "Leave a request", "Работаем ежедневно. Запись можно выбрать в пару нажатий.": "We work every day. You can book in just a couple of taps.", "Имитация интеграции · YCLIENTS": "YCLIENTS integration simulation", "Выберите дату:": "Choose a date:", "Какое время удобно?": "What time works for you?", "Как к вам обращаться?": "What should we call you?", "Введите имя": "Enter your name", "Оставьте номер телефона": "Leave your phone number", "Коротко опишите ваш запрос": "Briefly describe your request", "Комментарий": "Comment", "Готово! Демонстрационная заявка передана администратору.": "Done! The demo lead has been sent to the administrator.",
  "Здравствуйте! Это демо для": "Hello! This is a demo for", "Демо «": "Demo “", "Откройте мини-приложение": "Open the Mini App", "Выберите подходящий вариант:": "Choose an option:", "Здесь бот отвечает на частые вопросы и помогает выбрать следующий шаг.": "Here the bot answers common questions and helps choose the next step.", "Посмотреть услуги": "View services", "Выбрать услугу": "Choose a service", "Это первое обращение?": "Is this your first request?", "Впервые": "First time", "Уже обращался": "Returning client", "Карточка клиента подготовлена. Что сделать дальше?": "The client card is ready. What should happen next?", "Отправить напоминание": "Send a reminder", "Главная": "Home", "Интерфейс адаптирован под бизнес": "The interface is tailored to the business", "Каталог услуг": "Service catalogue", "Мои заявки": "My requests", "Выберите услугу в каталоге:": "Choose a service from the catalogue:", "Вопрос": "Question", "Раздел": "Section", "Действие": "Action", "Как удобнее с вами связаться?": "How would you prefer to be contacted?", "Коротко опишите запрос": "Briefly describe your request", "Получить расчёт": "Get an estimate", "Вызвать мастера": "Call a specialist", "Срочный выезд": "Urgent visit", "Консультация специалиста": "Specialist consultation", "Лечение": "Treatment", "Выбрать курс": "Choose a course", "Пробный урок": "Trial lesson", "Купить объект": "Buy a property", "Снять объект": "Rent a property", "Оформить заказ": "Place an order", "Посмотреть меню": "View menu", "Забронировать столик": "Reserve a table", "Техническое обслуживание": "Maintenance", "Окрашивание": "Colouring", "Укладка": "Styling", "Оставьте телефон для подтверждения": "Leave a phone number for confirmation", "Оставьте телефон для связи": "Leave a phone number to get in touch", "Оставьте телефон, чтобы подтвердить время": "Leave a phone number to confirm a time", "Введите детали": "Enter details", "Демо-сценарий адаптирован под выбранную отрасль": "Scenario adapted to the selected industry", "Сценарий адаптирован под указанную отрасль": "Scenario adapted to the specified industry",
  "Помогу рассчитать уборку.": "I’ll help estimate your cleaning.", "Что нужно убрать?": "What needs to be cleaned?", "Квартира": "Apartment", "Дом": "House", "Офис": "Office", "Сколько комнат?": "How many rooms?", "Примерная площадь?": "Approximate area?", "Нужны дополнительные услуги?": "Do you need additional services?", "Предварительная стоимость:": "Estimated price:", "Финальную стоимость подтвердит менеджер.": "The manager will confirm the final price.", "Вернуться": "Go back", "Введите телефон": "Enter your phone number", "Спасибо!": "Thank you!", "Демонстрационная заявка отправлена менеджеру.": "The demo lead has been sent to the manager.",
  "Что хотите сделать с автомобилем?": "What would you like to do with your car?", "Марка автомобиля?": "Car make?", "Когда удобно приехать?": "When would you like to visit?", "Оставьте номер телефона, и администратор подтвердит свободное время.": "Leave your phone number and the administrator will confirm an available time.", "Заявка передана сервису.": "The request has been sent to the service centre.", "Помогу подобрать обучение.": "I’ll help choose a course.", "Ваш уровень?": "What is your level?", "Какая цель?": "What is your goal?", "Хотите записаться на пробное занятие?": "Would you like to book a trial lesson?", "Да": "Yes", "Сначала консультация": "Consultation first", "Как вас зовут?": "What is your name?", "Оставьте телефон": "Leave your phone number", "Менеджер получил демонстрационную заявку на пробный урок.": "The manager received the demo request for a trial lesson.", "К какому специалисту хотите записаться?": "Which specialist would you like to book?", "Стоматолог-терапевт": "Dentist", "Ортодонт": "Orthodontist", "Гигиенист": "Dental hygienist", "Что вас беспокоит?": "What is bothering you?", "Профилактический осмотр": "Preventive check-up", "Лечение зуба": "Dental treatment", "Консультация": "Consultation", "Выберите удобный день:": "Choose a convenient day:", "Выберите время:": "Choose a time:", "Оставьте номер телефона для подтверждения записи": "Leave your phone number to confirm the booking", "Спасибо! Демонстрационная запись передана администратору клиники.": "Thank you! The demo booking has been sent to the clinic administrator.",
  "Что случилось?": "What happened?", "Насколько срочно нужна помощь?": "How urgently do you need help?", "В каком районе находится объект?": "Which district is the property in?", "Например, Хамовники": "For example, Khamovniki", "Номер телефона?": "Phone number?", "Спасибо.\nЗаявка передана мастеру. С вами свяжутся для уточнения деталей.": "Thank you.\nThe request has been sent to a specialist. They will contact you to clarify the details.", "Помогу подобрать подходящие варианты.": "I’ll help find suitable options.", "Тип объекта?": "Property type?", "Бюджет?": "Budget?", "Количество комнат?": "Number of rooms?", "Какой район рассматриваете?": "Which district are you considering?", "Введите район": "Enter a district", "Ваш демонстрационный запрос передан специалисту.": "Your demo request has been sent to a specialist.",
  "Помогу передать вашу задачу нужному специалисту.": "I’ll send your task to the right specialist.", "Что требуется?": "What do you need?", "Размер компании?": "Company size?", "Когда хотите запустить проект?": "When would you like to launch the project?", "Телефон / Telegram": "Phone / Telegram", "Контакт для связи": "Contact details", "Спасибо.\nДемонстрационная заявка сформирована и передана специалисту.": "Thank you.\nThe demo lead has been created and sent to a specialist.",
  "Узнать об услугах": "Learn about services", "Получить консультацию": "Get a consultation", "Коротко опишите, что вам нужно": "Briefly describe what you need", "Ваш запрос": "Your request", "Как удобнее получить ответ?": "How would you prefer to receive an answer?", "В Telegram": "In Telegram", "Звонком": "By phone", "По почте": "By email", "Оставьте контакт для связи": "Leave your contact details",
  "Стрижка": "Haircut", "мин": "min", "SPA-программа": "SPA programme", "Массаж": "Massage", "Завтра": "Tomorrow", "На выходных": "This weekend", "До 40 м²": "Up to 40 m²", "40–70 м²": "40–70 m²", "70–100 м²": "70–100 m²", "100+ м²": "100+ m²", "Мытьё окон": "Window cleaning", "Холодильник": "Fridge", "Духовка": "Oven", "Без дополнительных услуг": "No extra services", "ТО": "Maintenance", "Диагностика": "Diagnostics", "Детейлинг": "Detailing", "Шиномонтаж": "Tyres", "Другая": "Other", "Английский": "English", "Программирование": "Programming", "Подготовка к экзаменам": "Exam preparation", "Начинающий": "Beginner", "Средний": "Intermediate", "Продвинутый": "Advanced", "Для работы": "For work", "Для учёбы": "For study", "Для себя": "For myself", "Сантехника": "Plumbing", "Электрика": "Electrical", "Кондиционер": "Air conditioning", "Бытовая техника": "Home appliances", "В течение 2–3 дней": "Within 2–3 days", "Не срочно": "Not urgent", "Купить": "Buy", "Снять": "Rent", "До 10 млн": "Up to 10m", "10–20 млн": "10–20m", "20+ млн": "20m+", "Telegram-бот": "Telegram bot", "Mini App": "Mini App", "AI-автоматизация": "AI automation", "Интеграция CRM": "CRM integration", "Как можно быстрее": "As soon as possible", "В течение месяца": "Within a month", "Изучаю варианты": "Exploring options", "Какое действие должен выполнить клиент?": "What action should the client take?", "Перейти к записи": "Go to booking", "К какому сегменту отнести клиента?": "Which segment should the client belong to?", "Повторное обращение": "Repeat enquiry", "Демо: карточка лида подготовлена. Выберите следующее действие:": "Demo: the lead card is ready. Choose the next action:", "Передать менеджеру": "Send to manager", "Запустить серию сообщений": "Start a message sequence", "Какой раздел мини-приложения открыть?": "Which Mini App section should open?", "Каталог и услуги": "Catalogue and services", "Расписание и запись": "Schedule and booking", "Личный раздел доступен. Что показать клиенту?": "The client area is available. What should the client see?", "Мои записи": "My bookings", "Персональные предложения": "Personal offers", "Демо: интерфейс сформировал персональный путь клиента.": "Demo: the interface has created a personal client journey.", "Продолжить к услуге": "Continue to service", "Что нужно улучшить в действующем боте?": "What needs improving in the current bot?", "Обновить сообщения": "Update messages", "Добавить сценарий": "Add a scenario", "Как быстро требуется изменение?": "How quickly is the change needed?", "Срочно": "Urgent", "В плановом порядке": "Planned", "Демо: задача добавлена в план сопровождения и назначена специалисту.": "Demo: the task has been added to the support plan and assigned to a specialist.", "Посмотреть сценарий": "View scenario",
  "Как происходит взаимодействие": "How we work together", "Приём у стоматолога": "Dentist appointment", "Автомобиль": "Car", "Ваше имя": "Your name", "Время": "Time", "Выберите услугу": "Choose a service", "Вызов мастера": "Call a specialist", "Дата": "Date", "Действие клиента": "Client action", "Демонстрация автоматической воронки. Бот быстро квалифицирует обращение и передаёт его менеджеру.": "Automated funnel demonstration. The bot quickly qualifies the enquiry and sends it to a manager.", "Демонстрация продвинутого бота. Он сегментирует клиента, запускает автоматизацию и готовит лид для CRM.": "Advanced bot demonstration. It segments the client, starts automation and prepares a CRM lead.", "Демонстрация Telegram мини-приложения. Клиент открывает интерфейс с услугами, записью и персональным разделом.": "Telegram Mini App demonstration. The client opens an interface with services, booking and a personal area.", "Детали": "Details", "Доп. услуга": "Extra service", "Дополнительные услуги": "Additional services", "Запись в сервис": "Service booking", "Запись и услуги": "Booking and services", "Запись к специалисту": "Specialist booking", "Запрос": "Request", "Заявка": "Lead", "Имя": "Name", "Интерес": "Interest", "Канал связи": "Contact channel", "Квалификация запроса": "Lead qualification", "Квалифицировать запрос": "Qualify the request", "Комнаты": "Rooms", "Контакт": "Contact", "Личный раздел": "Personal area", "Направление": "Subject", "Настроить напоминание": "Set a reminder", "Открыть меню": "Open menu", "Площадь": "Area", "Причина обращения": "Reason for enquiry", "Программы и запись": "Programmes and booking", "Раздел мини-приложения": "Mini App section", "Расчёт": "Estimate", "Расчёт уборки": "Cleaning estimate", "Сегмент": "Segment", "Следующее действие": "Next action", "Специалист": "Specialist", "Срок": "Timeline", "Срочность": "Urgency", "Стартовый путь": "Starting path", "Статус": "Status", "Тип": "Type", "Тип проблемы": "Issue type", "Уровень": "Level", "Услуга": "Service", "Формат": "Format", "Целевое действие": "Target action", "Цель": "Goal", "Что важно сделать до передачи заявки?": "What is important before handing off the lead?", "CRM · Демо": "CRM · Demo", "Мини-приложение · Демо": "Mini App · Demo", "Telegram администратору": "Telegram administrator"
};

function translationMap(language: Language) { return language === "en" ? phrases : Object.fromEntries(Object.entries(phrases).map(([ru, en]) => [en, ru])); }
function translateValue(value: string, map: Record<string, string>) { return Object.entries(map).sort(([first], [second]) => second.length - first.length).reduce((translated, [from, to]) => translated.split(from).join(to), value); }
function translateText(root: HTMLElement, language: Language) {
  const map = translationMap(language);
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); const nodes: Text[] = [];
  while (walker.nextNode()) nodes.push(walker.currentNode as Text);
  nodes.forEach((node) => { const original = node.nodeValue ?? ""; const translated = translateValue(original, map); if (translated !== original) node.nodeValue = translated; });
  root.querySelectorAll<HTMLElement>("[placeholder], [title], [aria-label]").forEach((element) => ["placeholder", "title", "aria-label"].forEach((attribute) => { const original = element.getAttribute(attribute); if (!original) return; const translated = translateValue(original, map); if (translated !== original) element.setAttribute(attribute, translated); }));
}

export function LocaleProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("ru");
  useEffect(() => { document.documentElement.lang = language; const root = document.body; translateText(root, language); const observer = new MutationObserver(() => translateText(root, language)); observer.observe(root, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ["placeholder", "title", "aria-label"] }); return () => observer.disconnect(); }, [language]);
  const value = useMemo(() => ({ language, toggle: () => setLanguage((current) => current === "ru" ? "en" : "ru"), t: (text: string) => translateValue(text, translationMap(language)) }), [language]);
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>;
}
export function useLocale() { return useContext(LocaleContext); }
export function LanguageToggle() { const { language, toggle } = useContext(LocaleContext); return <button className="language-toggle" onClick={toggle} aria-label="Сменить язык">{language === "ru" ? "EN" : "RU"}</button>; }
